In [1]:
import sklearn

In [2]:
# Task 1
from sklearn.datasets import load_wine
wine = load_wine()

In [3]:
# Task 2---- Split the datset wine

from sklearn.model_selection import train_test_split

In [4]:
X_train,X_test,y_train,y_test = train_test_split(wine.data, wine.target, random_state=925)

In [5]:
# Check the shape 

print(" X_train shape:", X_train.shape)
print(" y_train shape:", y_train.shape)






 X_train shape: (133, 13)
 y_train shape: (133,)


In [6]:
print(" X_test shape:", X_test.shape)
print(" y_test shape:", y_test.shape)

 X_test shape: (45, 13)
 y_test shape: (45,)


In [7]:
# Check the description

print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [8]:
# Task 3

# Start by normalising the training data

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [9]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:
# To apply the transformation, to actually scale the data
# we use the transform method of the scaler.

X_train_scaled = scaler.transform(X_train)
# print dataset properties before and after scaling
print(X_train_scaled.shape)
print(X_train.min(axis=0))
print(X_train.max(axis=0))
print(X_train_scaled.min(axis=0))
print(X_train_scaled.max(axis=0))

(133, 13)
[1.103e+01 7.400e-01 1.360e+00 1.060e+01 7.000e+01 1.100e+00 4.700e-01
 1.400e-01 4.200e-01 1.280e+00 4.800e-01 1.270e+00 2.780e+02]
[1.483e+01 5.800e+00 3.230e+00 3.000e+01 1.620e+02 3.880e+00 5.080e+00
 6.300e-01 3.580e+00 1.080e+01 1.710e+00 4.000e+00 1.680e+03]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
# We can see that the transformed data has the same shape as the original
# data—the features are simply shifted and scaled
# All of the features are now between 0 and 1

In [12]:
# To apply the SVM to the scaled data, we also need to transform the test set

X_test_scaled = scaler.transform(X_test)
# print test data properties after scaling
print(X_test_scaled.min(axis=0))
print(X_test_scaled.max(axis=0))

[ 0.15263158  0.03162055  0.18716578  0.04123711  0.10869565 -0.04316547
 -0.02819957 -0.02040816 -0.00316456  0.08193277  0.07317073  0.02197802
  0.0085592 ]
[0.97894737 0.94268775 0.80213904 0.74226804 0.60869565 0.86330935
 0.69848156 1.06122449 0.78797468 1.23109244 0.78861789 0.93406593
 0.78245364]


In [13]:
# For the test set, after scaling, the minimum and maximum are not 0 and 1

In [14]:
# Now let’s see the effect of using the MinMaxScaler on learning the SVM.
# First, let’s fit the SVM on the original data for comparison

from sklearn.svm import SVC
X_train, X_test, y_train, y_test = train_test_split(wine.data,
wine.target, random_state=925)
svm = SVC(C=100)
svm.fit(X_train, y_train)
print(svm.score(X_test, y_test))

0.35555555555555557


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [16]:
# Now, let’s apply SVM to the data normalized by MinMaxScaler

X_test_scaled = scaler.transform(X_test)
# learning an SVM on the scaled training data:
svm.fit(X_train_scaled, y_train)
# scoring on the scaled test set:
print(svm.score(X_test_scaled, y_test))

1.0


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [17]:
# I will try the 3rd task again as I have understood I should do 

import numpy as np
from sklearn import svm

In [18]:
X_train,X_test,y_train,y_test = train_test_split(wine.data, wine.target, random_state=925)

print(" X_train shape:", X_train.shape)
print(" y_train shape:", y_train.shape)

print(" X_test shape:", X_test.shape)
print(" y_test shape:", y_test.shape)


 X_train shape: (133, 13)
 y_train shape: (133,)
 X_test shape: (45, 13)
 y_test shape: (45,)


In [19]:
# We can now quickly sample a training set for testing (evaluating) our classifier
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf.score(X_test, y_test)

1.0

In [20]:
# Obviously this is overfitting

In [21]:
# The simplest way to use cross-validation is to call the cross_val_score helper function on the estimator and the dataset.
# The following example demonstrates how to estimate the accuracy of a linear kernel support vector machine on the wine dataset by splitting the data, 
# fitting a model and computing the score 5 consecutive times (with different splits each time)

from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=925)
scores = cross_val_score(clf, X_train, y_train, cv=5)
scores

array([0.92857143, 0.89285714, 0.92592593, 0.92      , 1.        ])

In [22]:
# I also want to check the cross validation used in lab 6, to see the difference

best_score = 0
for gamma in [0.001, 0.01, 0.1, 1, 10, 100]:
    for C in [0.001, 0.01, 0.1, 1, 10, 100]:
       # for each combination of parameters, train an SVC
        svm = SVC(gamma=gamma, C=C)
       # perform cross-validation
        scores = cross_val_score(svm, X_train, y_train, cv=5)
        # compute mean cross-validation accuracy
        score = np.mean(scores)
       # if we got a better score, store the score and parameters
        if score > best_score:
            best_score = score
            best_C = C
            best_gamma = gamma
# rebuild a model on the full training set
svm = SVC(C=best_C, gamma=best_gamma)
svm.fit(X_train, y_train)
test_score = svm.score(X_test, y_test)
print("Best CV score:", best_score)
print("Best parameters C and gamma:", best_C, best_gamma)
print("Test set score with best parameters:", test_score)


Best CV score: 0.6935555555555556
Best parameters C and gamma: 100 0.001
Test set score with best parameters: 0.8222222222222222


In [23]:
# Above I have normalised the data and I have done linear SVM which is wrong

In [24]:
# 1

import sklearn
from sklearn.datasets import load_wine
wine = load_wine()

In [25]:
# Check the description

print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [26]:

# 2---- Split the datset wine

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(wine.data, wine.target, random_state=925)

In [27]:
# Check the shape 

# Train
print(" X_train shape:", X_train.shape)
print(" y_train shape:", y_train.shape)
# And test
print(" X_test shape:", X_test.shape)
print(" y_test shape:", y_test.shape)

 X_train shape: (133, 13)
 y_train shape: (133,)
 X_test shape: (45, 13)
 y_test shape: (45,)


In [33]:
print(wine.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [34]:
print(wine.data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [29]:
# 3 Cross validation on the training test- SVM score

import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import cross_val_score

In [30]:
clf = svm.SVC(random_state=925)

In [31]:
scores = cross_val_score(clf, X_train, y_train, cv=5)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

In [32]:
scores

array([0.42857143, 0.42857143, 0.40740741, 0.44      , 0.44      ])

In [35]:
scores = cross_val_score(clf, X_train, y_train, cv=10)
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

array([0.4       , 0.4       , 0.4       , 0.46153846, 0.46153846,
       0.46153846, 0.46153846, 0.41666667, 0.41666667, 0.41666667])

In [40]:
scores = cross_val_score(clf, X_train, y_train, cv=5)
clf = svm.SVC(gamma= 'auto',  random_state=925)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

In [42]:
svm=SVC()
cross_val_score(svm, X_train, y_train, cv=5)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

array([0.42857143, 0.42857143, 0.40740741, 0.44      , 0.44      ])

In [48]:
# For task 3 i can stick to 
# Please bear in mind the data is not normalised here

import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import cross_val_score

svm=SVC()
svm.fit( X_train, y_train)

cross_val_score(svm, X_test, y_test, cv=5)


# Another ex:

from sklearn.svm import SVC
X_train, X_test, y_train, y_test = train_test_split(cancer.data,
cancer.target, random_state=925)
svm = SVC()
svm.fit(X_train, y_train)
print(svm.score(X_test, y_test)



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

array([0.3       , 0.33333333, 0.33333333, 0.33333333, 0.375     ])

In [49]:
cross_val_score(svm, X_train, y_train, cv=5)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

array([0.42857143, 0.42857143, 0.40740741, 0.44      , 0.44      ])

In [50]:
# Task 5 and 6 

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline


In [51]:
pipe_long = Pipeline([("scaler", StandardScaler()), ("svm", SVC())])
pipe_short = make_pipeline(StandardScaler(), SVC())

In [52]:
pipe_short.steps

[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)),
 ('svc', SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
      decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
      kernel='rbf', max_iter=-1, probability=False, random_state=None,
      shrinking=True, tol=0.001, verbose=False))]

In [55]:
pipe = make_pipeline(StandardScaler(), SVC())
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

0.9777777777777777

In [56]:
from sklearn.preprocessing import MinMaxScaler
pipe_long = Pipeline([("scaler",  MinMaxScaler()), ("svm", SVC())])
pipe_short = make_pipeline( MinMaxScaler(), SVC())

In [57]:
pipe_short.steps

[('minmaxscaler', MinMaxScaler(copy=True, feature_range=(0, 1))),
 ('svc', SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
      decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
      kernel='rbf', max_iter=-1, probability=False, random_state=None,
      shrinking=True, tol=0.001, verbose=False))]

In [58]:
pipe = make_pipeline(MinMaxScaler(), SVC())
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


1.0

In [59]:
from sklearn.preprocessing import Normalizer
pipe_long = Pipeline([("scaler",  Normalizer()), ("svm", SVC())])
pipe_short = make_pipeline( Normalizer(), SVC())

In [60]:
pipe_short.steps

[('normalizer', Normalizer(copy=True, norm='l2')),
 ('svc', SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
      decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
      kernel='rbf', max_iter=-1, probability=False, random_state=None,
      shrinking=True, tol=0.001, verbose=False))]

In [61]:
pipe = make_pipeline(Normalizer(), SVC())
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.3111111111111111

In [62]:
from sklearn.preprocessing import RobustScaler
pipe_long = Pipeline([("scaler",  RobustScaler()), ("svm", SVC())])
pipe_short = make_pipeline( RobustScaler(), SVC())

In [63]:
pipe_short.steps

[('robustscaler',
  RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
               with_scaling=True)),
 ('svc', SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
      decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
      kernel='rbf', max_iter=-1, probability=False, random_state=None,
      shrinking=True, tol=0.001, verbose=False))]

In [64]:
pipe = make_pipeline(RobustScaler(), SVC())
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


1.0

In [ ]:
# According the the figures, StandardScaler looks like the most appropriate normalization method, MinMax and Robust overfits while 
# Normalizer underfits

In [65]:
pipe = make_pipeline(StandardScaler(), SVC())
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

0.9777777777777777

In [79]:
for gamma in [0.001, 0.01, 0.1, 1, 10, 100]:
    for C in [0.001, 0.01, 0.1, 1, 10, 100]:
       # for each combination of parameters, train an SVC
        svm = SVC(gamma=gamma, C=C)
       # perform cross-validation
        scores = cross_val_score(svm, X_train, y_train, cv=5)
        # compute mean cross-validation accuracy
        score = np.mean(scores)
       # if we got a better score, store the score and parameters
        if score > best_score:
            best_score = score
            best_C = C
            best_gamma = gamma
# rebuild a model on the full training set
svm = SVC(C=best_C, gamma=best_gamma)
svm.fit(X_train, y_train)
test_score = svm.score(X_test, y_test)
print("Best CV score:", best_score)
print("Best parameters C and gamma:", best_C, best_gamma)
print("Test set score with best parameters:", test_score)


Best CV score: 0.6935555555555556
Best parameters C and gamma: 100 0.001
Test set score with best parameters: 0.8222222222222222


In [80]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100],
'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}

In [81]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(SVC(), param_grid, cv=5)

In [82]:
grid_search.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100],
                         'gamma': [0.001, 0.01, 0.1, 1, 10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [83]:
grid_search.score(X_test, y_test)


0.8222222222222222

In [84]:
print(grid_search.best_params_)
print(grid_search.best_score_)

{'C': 100, 'gamma': 0.001}
0.6917293233082706


In [96]:
# Task 8

from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(solver='lbfgs', activation='tanh', random_state=925,
hidden_layer_sizes=[10]).fit(X_train,y_train)

# By default, the MLP uses 100 hidden nodes, which is quite a lot for this
# small dataset

In [93]:


mlp.fit(X_train, y_train)
scores = cross_val_score(mlp, X_train, y_train, cv=5)
scores

array([0.42857143, 0.42857143, 0.40740741, 0.44      , 0.44      ])

In [94]:
scores = cross_val_score(mlp, X_test, y_test, cv=5)
scores

array([0.3       , 0.66666667, 0.33333333, 0.33333333, 0.375     ])